### PR TITLE
Pre-Jovo Port

### PR DESCRIPTION
**Pull request by warpaltarpers**
### What has been changed/added?
* Voice parsing fixes

### Known Issues
* It's been a while, I don't remember TBH

### Contributors
* **Chandler Davis** - [photonfighter](https://github.com/photonfighter/)

### CODE REVIEW

**Comment by warpaltarpers** [comment]
Would probably also include rewriting a lot of the non-code files and GitHub stuff, i.e. repo name, README, etc.

**Comment by photonfighter** [comment]
I'm in, let's do it

**Comment by photonfighter** [comment]
I have no idea how to actually merge/review, pls help

**Comment by warpaltarpers** [comment]
I like how as soon as I want to start working on this because of quarantine, my thesis deadlines get moved up 💀

**Pull request merged**
